apiVersion: v1
kind: Service
metadata:
  name: jwt-validator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
      app: jwt-validator
  type: NodePort
