apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-validator1
  labels:
    app: jwt-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-validator
  template:
    metadata:
      labels:
        app: jwt-validator
    spec:
      containers:
        - name: jwt-validator
          image: "igor0208/jwt-validator:3.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      