apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-validator
  labels:
    app: jwt-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-validator
  template:
    metadata:
      labels:
        app: jwt-validator
    spec:
      containers:
        - name: jwt-validator
          image: "757474363232.dkr.ecr.us-east-1.amazonaws.com/jwt-validator:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      