apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-validator
  labels:
    app: jwt-validator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jwt-validator
  template:
    metadata:
      labels:
        app: jwt-validator
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      