apiVersion: v1
kind: Service
metadata:
  name: jwt-validator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
  selector:
      app: jwt-validator
  type: NodePort
